name: C Make

on: [push]

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OPENMPI_VERSION: 4.0.2
    steps:
    - name: download
      run: wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-${OPENMPI_VERSION}.tar.gz
    - name: extract
      run: tar -xvf ./openmpi-${OPENMPI_VERSION}.tar.gz
    - name: configure
      run: ./openmpi-${OPENMPI_VERSION}/configure --prefix="/usr/local"
    - name: install
      run: |
        make -j
        sudo make install
        sudo ldconfig
    - uses: actions/checkout@master
      with:
        fetch_depth: 1
    - name: make
      run: make
