name: C CI

on: [push]

jobs:
  openmpi:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}
    steps:
    - name: download-openmpi
      run: wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.2.tar.gz
    - name: extract-openmpi
      run: tar -xvf ./openmpi-4.0.2.tar.gz && cd openmpi-4.0.2
    - name: configure-openmpi
      run: ./configure --prefix="/home/$USER/.openmpi"
    - name: install-openmpi
      run: make -j && sudo make install
  build:
    runs-on: ubuntu-latest
    needs: [openmpi]
    env:
      PATH: $PATH:/home/$USER/.openmpi/bin
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/home/$USER/.openmpi/lib/
    steps:
    - uses: actions/checkout@master
      with:
        fetch_depth: 1
    - name: make
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: make
