name: C CI

on: [push]

jobs:
  openmpi:
    runs-on: ubuntu-latest
    env:
      OPENMPI_VERSION: 4.0.2
    steps:
    - name: download-openmpi
      run: wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-${OPENMPI_VERSION}.tar.gz
    - name: extract-openmpi
      run: tar -xvf ./openmpi-${OPENMPI_VERSION}.tar.gz
    - name: configure-openmpi
      run: ./openmpi-${OPENMPI_VERSION}/configure --prefix="/home/${USER}/.openmpi"
    - name: install-openmpi
      run: |
        make -j
        sudo make install
    - name: set-openmpi-envs
      run: |
        echo "::add-path::/home/${USER}/.openmpi/bin"
        echo "::set-env name=LD_LIBRARY_PATH::/home/${USER}/.openmpi/lib/"
  build:
    runs-on: ubuntu-latest
    needs: [openmpi]
    steps:
    - uses: actions/checkout@master
      with:
        fetch_depth: 1
    - name: see-openmpi-envs
      run: |
        echo ${PATH}
        echo ${LD_LIBRARY_PATH}
        which mpicc
        which mpiexec
    - name: make
      run: make
