name: C CI

on: [push]

jobs:
  openmpi:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}
    steps:
    - name: download-openmpi
      run: wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.2.tar.gz
    - name: extract-openmpi
      run: tar -xvf ./openmpi-4.0.2.tar.gz
    - name: WHERE-THE-FUCK-AM-I-NOW
      run: pwd
    - name: WHAT-THE-FUCK-IS-HERE
      run: ls -la
    - name: configure-openmpi
      run: ./openmpi-4.0.2/configure --prefix="/home/$USER/.openmpi"
    - name: install-openmpi
      run: |
        make -j
        sudo make install
  build:
    runs-on: ubuntu-latest
    needs: [openmpi]
    steps:
    - uses: actions/checkout@master
      with:
        fetch_depth: 1
    - name: set-openmpi-path
      run: |
        echo "::set-env name=PATH::${PATH}:/home/$USER/.openmpi/bin"
        echo "::set-env name=LD_LIBRARY_PATH::${LD_LIBRARY_PATH}:/home/$USER/.openmpi/lib/"
    - name: make
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: make
