name: C CI

on: [push]

jobs:
  openmpi:
    runs-on: ubuntu-latest
    env:
      OPENMPI_VERSION: 4.0.2
    steps:
    - name: download
      run: wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-${OPENMPI_VERSION}.tar.gz
    - name: extract
      run: tar -xvf ./openmpi-${OPENMPI_VERSION}.tar.gz
    - name: configure
      run: ./openmpi-${OPENMPI_VERSION}/configure --prefix="/usr/local"
    - name: install
      run: |
        make -j
        sudo make install
  build:
    runs-on: ubuntu-latest
    needs: [openmpi]
    steps:
    - uses: actions/checkout@master
      with:
        fetch_depth: 1
    - name: check-openmpi
      run: |
        which mpicc
        which mpiexec
    - name: make
      run: make
